<?php
require_once('../config/tcpdf_config.php');
require_once('../tcpdf.php');
include('../../../DBConnect_UBMv1.php');
$conn = new mysqli($DBServer, $DBUser, $DBPass, $DBName);
// check connection
if ($conn->connect_error) {
trigger_error('Database connection failed: '  . $conn->connect_error, E_USER_ERROR);
}
$sqlsel = "SELECT * FROM ubm_model_jobDescriptions ORDER BY title ASC";
//Select all
$rs1=$conn->query($sqlsel);
// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {
    //Page header
    public function Header() {
        // Logo
                                //        $image_file = 'images/tcpdf_logo1.jpg';
        // $this->Image($image_file, 15, 5, 30, '', 'jpg', '', 'T', false, 300, '', false, false, 0, false, false, false);
    }
    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('dejavusans', 'I', 10);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}
// create new PDF document
$pdf = new MYPDF('l', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Nicola Assuni');
$pdf->SetTitle('Lista djelatnika na terenu');
$pdf->SetSubject('Subject');
$pdf->SetKeywords('TCPDF, PDF, tablica, test, guide');
// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);
// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
//set margins
//$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetMargins(PDF_MARGIN_LEFT, 40, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
//set some language-dependent strings
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
require_once(dirname(__FILE__).'/lang/eng.php');
$pdf->setLanguageArray($l);
}
// ---------------------------------------------------------
// set font
$pdf->SetFont('times', 'B', 20);
$tbl_footer = '</table>';
if($rs1 === false) {
trigger_error('Wrong SQL: ' . $sqlsel . ' Error: ' . $conn->error, E_USER_ERROR);
} else {
if(mysqli_num_rows($rs1)>0){
$numberOfJobDescriptions = mysqli_num_rows($rs1);
$tableCounter = 0;
while ($row = $rs1->fetch_assoc()) {
$tableCounter +=1;
// add a page
$tableVar = '    
<div>
    <p>
    <a><strong>Job Description Attributes</strong></a>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="125" valign="top">
                    <p>
                    Grade Level
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
            <tr>
                <td width="125" valign="top">
                    <p>
                    Security Level <em>(Generated by the attached job descriptions)</em>
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
            <tr>
                <td width="125" valign="top">
                    <p>
                    Age Requirements <em>(Generated by the attached job descriptions)</em>
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
    <strong> </strong>
    </p>
</div>
<br clear="all"/>
<div>
    <p>
    <a title="What is the objective or mission of this position:"><strong>Objective of Job Description</strong></a>
    </p>
    <p>
    ____________________________________________________________________________________
    </p>
    <p>
    <strong> </strong>
    </p>
    <p>
    <a
    title=" This section should briefly describe specific job tasks with details of the major duties and/or responsibilities for performing the job. See object definitions in the INDEX section for examples "
    >
    <strong>Essential Duties and Responsibilities:</strong>
    </a>
    ____________________________________________________________________________________<strong></strong>
    </p>
</div>
<strong>
<br clear="all"/>
</strong>
<div>
    <p>
    <strong> </strong>
    </p>
</div>
<br clear="all"/>
<div>
    <p>
    <strong>Education Requirements: </strong>
    <em></em>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                    1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    3)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    4)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
    <strong> </strong>
    </p>
    <p>
    <strong>Physical Demands:</strong>
    <em> </em>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                    1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
    <strong>Qualification Requirements:</strong>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                    1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    3)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    4)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
    <strong> </strong>
    </p>
    <p>
    <strong>Work Environment: </strong>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                    1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                    2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
</div>';
$pdf->AddPage();
// set cell padding
$pdf->setCellPaddings(1, 1, 1, 1);
// set cell margins
$pdf->setCellMargins(1, 1, 1, 1);
// set color for background
$pdf->SetFillColor(220, 255, 220);
// Multicell test
// writeHTMLCell ($w, $h, $x, $y, $html='', $border=0, $ln=0, $fill=false, $reseth=true, $align='', $autopadding=true)
// print a block of text using Write()
$pdf->writeHTMLCell(00, 300, 0, 0, $tableVar, 0, 0, '', '', true);
}
//        echo $_GET['callback'] . '(' . json_encode($all_items) . ')';       //Output $all_items array in json encoded format.
}else{
$tbl .= '
<tr>
    <td>Query Returned no results</td>
</tr>
';
}
}
// output the HTML content
//$pdf->writeHTML($tbl , true, false, false, false, '');
//$pdf->lastPage();
// ---------------------------------------------------------
//Close and output PDF document
$pdf->Output('ubm_JD_report.pdf', 'I');
?>