<?php
require_once('../config/tcpdf_config.php');
require_once('../tcpdf.php');
include('../../../DBConnect_UBMv1.php');
$conn = new mysqli($DBServer, $DBUser, $DBPass, $DBName);
// check connection
	if ($conn->connect_error) {
	  trigger_error('Database connection failed: '  . $conn->connect_error, E_USER_ERROR);
	}
$sqlsel = "SELECT * FROM ubm_model_positions ORDER BY title ASC";
//Select all 
$rs1=$conn->query($sqlsel);

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {
    //Page header
    public function Header() {
        // Logo
        $image_file = K_PATH_IMAGES.'logo_example.jpg';
        $this->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        // Set font
        $this->SetFont('helvetica', 'B', 20);
        // Title
        $this->SetXY(15, 5);
        $this->Cell(0, 10, 'Legal Entity :', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetXY(15, 15);
        $this->Cell(0, 10, 'System Title :', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetXY(15, 25);
        $this->Cell(0, 10, 'App Title :', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->SetXY(15, 35);
        $this->Cell(0, 10, 'Position Title :', 0, false, 'C', 0, '', 0, false, 'M', 'M');
    }
    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('dejavusans', 'I', 10);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// create new PDF document
$pdf = new MYPDF('p', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Jesse Spencer');
$pdf->SetTitle('Position Product Template');
$pdf->SetSubject('Subject');
$pdf->SetKeywords('PS, Position, UBM');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
//$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 100, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

//set some language-dependent strings
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	require_once(dirname(__FILE__).'/lang/eng.php');
	$pdf->setLanguageArray($l);
}
// ---------------------------------------------------------

// set font
$pdf->SetFont('times', 'B', 20);
$tbl_style = '<style>
table {
   border-collapse: collapse;
   border-spacing: 0;
   margin: 0 10px;
}
tr {
   padding: 3px 0;
}

th {
   background-color: #CCCCCC;
   border: 1px solid #F5820F;
   color: #333333;
   font-family: trebuchet MS;
   font-size: 10px;
   padding-bottom: 4px;
   padding-left: 6px;
   padding-top: 5px;
   text-align: left;
}
td {
   background-color: #EEEEEE;
   border: 2px solid #F5820F;
   font-size: 12px;
   color: #5511FF;
   padding: 3px 7px 2px;
   text-align: left;

}
</style>';
$tbl_header = '
<table id="gallerytab" width="25%" cellspacing="0" cellpadding="2" border="0">
    <tr>
      <th colspan="2">Position Attributes</th>
    </tr>';
$tbl_footer = '</table>';
$tableVar = ''; 
if($rs1 === false) {
  trigger_error('Wrong SQL: ' . $sqlsel . ' Error: ' . $conn->error, E_USER_ERROR);
} else {
	if(mysqli_num_rows($rs1)>0){
		$numberOfPositions = mysqli_num_rows($rs1);
		$tableCounter = 0;
		while ($row = $rs1->fetch_assoc()) {
			$tableCounter +=1;
			// add a page
			 $tableVar = '	   
         <div>
    <p>
        <a name="LegalName"><strong>Job Description Attributes</strong></a>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="125" valign="top">
                    <p>
                        Grade Level
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
            <tr>
                <td width="125" valign="top">
                    <p>
                        Security Level <em>(Generated by the attached job descriptions)</em>
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
            <tr>
                <td width="125" valign="top">
                    <p>
                        Age Requirements <em>(Generated by the attached job descriptions)</em>
                    </p>
                </td>
                <td width="126" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong> </strong>
    </p>
</div>
<br clear="all"/>
<div>
    <p>
        <a href="#Objectiveofjobdescription" title="What is the objective or mission of this position"><strong>Objective of Job Description</strong></a>
        <strong>:</strong>
    </p>
    <p>
        ____________________________________________________________________________________
    </p>
    <p>
        <strong> </strong>
    </p>
    <p>
        <a
            href="#essentialdutiesandresponsibilities"
            title=" This section should briefly describe specific job tasks with details of the major duties and/or responsibilities for performing the job. See object definitions in the INDEX section for examples "
        >
            <strong>Essential Duties and Responsibilities</strong>
        </a>
        <strong>:</strong>
        ____________________________________________________________________________________<strong></strong>
    </p>
</div>
<strong>
    <br clear="all"/>
</strong>
<div>
    <p>
        <strong> </strong>
    </p>
</div>
<br clear="all"/>
<div>
    <p>
        <strong>Education Requirements: </strong>
        <em></em>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                        1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        3)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        4)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong> </strong>
    </p>
    <p>
        <strong>Physical Demands:</strong>
        <em> </em>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                        1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong>Qualification Requirements:</strong>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                        1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        3)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        4)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <strong> </strong>
    </p>
    <p>
        <strong>Work Environment: </strong>
    </p>
    <table border="1" cellspacing="0" cellpadding="0">
        <tbody>
            <tr>
                <td width="32" valign="top">
                    <p>
                        1)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
            <tr>
                <td width="32" valign="top">
                    <p>
                        2)
                    </p>
                </td>
                <td width="212" valign="top">
                </td>
            </tr>
        </tbody>
    </table>
</div>
<br clear="all"/>
<p>
    <strong>Position Object(s) Applied To:</strong>
</p>
<table border="1" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td width="63" valign="top">
                <p>
                    Reference
                </p>
            </td>
            <td width="441" valign="top">
                <p>
                    Position (PS) Title(s)
                </p>
            </td>
        </tr>
        <tr>
            <td width="63" valign="top">
            </td>
            <td width="441" valign="top">
            </td>
        </tr>
    </tbody>
</table>
<p>
    <strong></strong>
</p>
<p>
    <strong>Template Object(s) Applied To:</strong>
</p>
<table border="1" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td width="63" valign="top">
                <p>
                    Reference
                </p>
            </td>
            <td width="441" valign="top">
                <p>
                    Templates (TP) Title(s)
                </p>
            </td>
        </tr>
        <tr>
            <td width="63" valign="top">
            </td>
            <td width="441" valign="top">
            </td>
        </tr>
    </tbody>
</table>
<p>
    <a href="#Revisionhistory" title="This is where you will record any changes made to the specific application object">
        <strong>Revision History</strong>
        <strong>:</strong>
    </a>
</p>
<table border="1" cellspacing="0" cellpadding="0">
    <tbody>
        <tr>
            <td width="46" valign="top">
                <p>
                    Revision #
                </p>
            </td>
            <td width="63" valign="top">
                <p>
                    Date of Change
                </p>
            </td>
            <td width="272" valign="top">
                <p>
                    Description of Change
                </p>
            </td>
            <td width="134" valign="top">
                <p>
                    Authorized By
                </p>
            </td>
        </tr>
        <tr>
            <td width="46" valign="top">
                <p>
                    1.1
                </p>
            </td>
            <td width="63" valign="top">
                <p>
                    N/A
                </p>
            </td>
            <td width="272" valign="top">
                <p>
                    Launched Object
                </p>
            </td>
            <td width="134" valign="top">
                <p>
                    Business Model Manger
                </p>
            </td>
        </tr>
        <tr>
            <td width="46" valign="top">
            </td>
            <td width="63" valign="top">
            </td>
            <td width="272" valign="top">
            </td>
            <td width="134" valign="top">
            </td>
        </tr>
    </tbody>
</table>';
					$pdf->AddPage();

          // set cell padding
          $pdf->setCellPaddings(1, 1, 1, 1);
          // set cell margins
          $pdf->setCellMargins(1, 1, 1, 1);
          // set color for background
          $pdf->SetFillColor(220, 255, 220);          
          // Multicell test
          // writeHTMLCell ($w, $h, $x, $y, $html='', $border=0, $ln=0, $fill=false, $reseth=true, $align='', $autopadding=true)
          $pdf->writeHTMLCell(300, 5, 0, 45, $tbl_style.$tbl_header.$tableVar.$tbl_footer, 1, 0, '', '', true);
          $pdf->Ln('',true);
          // print a blox of text using multicell()
          $pdf->MultiCell('', 5, "[Physical Demands] ".$row['physical_demands'], 1, 'J', 1, 1, '' ,'', true);
          $pdf->Ln('',true);
          $pdf->MultiCell('', 5, "[Work Environment] ".$row['work_environment'], 1, 'J', 1, 1, '' ,'', true);
          $pdf->Ln('',true);
          $pdf->MultiCell('', 5, "[Conclusion] ".$row['conclusion'], 1, 'J', 1, 1, '' ,'', true);
			   
         }
//				echo $_GET['callback'] . '(' . json_encode($all_items) . ')';				//Output $all_items array in json encoded format.			
	}else{
		$tbl .= '
		   <tr>
		       <td>Query Returned no results</td>
		   </tr>
		';		
	}								
}


// output the HTML content
//$pdf->writeHTML($tbl , true, false, false, false, '');
//$pdf->lastPage();

// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('ubm_PS_report.pdf', 'I');
?>